### ISSUE TITLE
Codeverbesserungen

### ISSUE THREAD

**Issue by GiantTreeLP** [Stormfox2/Core#1]
Hi, 

du hattest ja um Kommentare zu deinem Code gebeten; hier sind meine:

[Core.java Zeile 10](https://github.com/Stormfox2/Core/blob/master/src/de/stormfox2/core/Core.java#L10):
Hier sollte man das `instance` Feld auf `private` setzen. Du hast ja schon einen Getter erstellt.
(Dies gilt analog auch überall sonst, wo du die Instanzen `public` gesetzt hast).

[Core.java Zeile 17&18](https://github.com/Stormfox2/Core/blob/master/src/de/stormfox2/core/Core.java#L17-L18):
Du erstellst hier zwei Instanzen, speicherst die aber nicht. Die Instanzen sind so nur über das `instance`-Feld verfügbar. Das verteilt deinen zentralen Objekte nur unnötig und gibt dir keine einfache Möglichkeit, sie zentral zu verwalten. Mein Tipp: behalte die Instanzen in der `Core.java`-Datei.

Die Klassen `Export` und `Import` sind leer; ich weiß nicht, was ich davon halten soll. So etwas hat eher Platz in einer `development`-Branch.

[Language.java Zeile 28](https://github.com/Stormfox2/Core/blob/master/src/de/stormfox2/core/language/Language.java#L28):
Beim SQL würde ich möglichst alle Spalten, Tabellen und Datenbanken escapen. Dann würde ich den SQL-Code selber in eine Konstante verschieben, der ändert sich ja nicht (`private static final`).

[MySQL.java Zeile 77](https://github.com/Stormfox2/Core/blob/master/src/de/stormfox2/core/mysql/MySQL.java#L77):
Ist der Objekttyp notwendig? Kann der `boolean` dort `null` sein?

[pom.xml Zeile 3](https://github.com/Stormfox2/Core/blob/master/pom.xml#L3): 
Ich bin mir sicher. dass die Gruppe `Core` unbeabsichtigt war, aber die ist nicht sehr aussagekräftig.

Sonst: Halte dich an die Konventionen (`groupId` und `artifactId` sollten klein sein), das machst du schon ganz gut. Nutze die automatische Formatierung (das ist ein Handgriff).
Vielleicht würde es sinnvoll sein, Ressourcen und Code zu trennen, wie Maven es generell tut.

**Comment by QF0xB** [comment]
Ich sollte alles gelöst haben.
